CREATE SEQUENCE SEQ_USERS
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE TABLE TBL_USERS(
    USER_ID NUMBER(19) DEFAULT SEQ_USERS.nextval PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL,
    PASSWORD VARCHAR2(20) NOT NULL
);