CREATE SEQUENCE SEQ_FOODS
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE TABLE TBL_FOODS (
    FOOD_ID INTEGER DEFAULT SEQ_FOODS.NEXTVAL NOT NULL,
    NAME VARCHAR2(100) NOT NULL,
    PORTION_WEIGHT VARCHAR2(30) NOT NULL,
    PROTEIN NUMBER(9,3) NOT NULL,
    CARBS NUMBER(9,3) NOT NULL,
    FATS NUMBER(9,3) NOT NULL,
    TOTAL_CALORIES NUMBER(9,3) NOT NULL
);